# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_patrol_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrol_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    calculate_elliptical_time_density as calculate_elliptical_time_density,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_path_layer as create_path_layer
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    load_local_spatial_file as load_local_spatial_file,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    collect_optional_layers as collect_optional_layers,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    compute_view_from_geodataframes as compute_view_from_geodataframes,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    set_viewport_settings as set_viewport_settings,
)

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_icmbio.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_icmbio.tasks import assign_sector as assign_sector
from ecoscope_workflows_ext_icmbio.tasks import (
    compute_sector_centroids as compute_sector_centroids,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    format_camera_trap_table as format_camera_trap_table,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    format_grid_summary_table as format_grid_summary_table,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    format_roadkill_event_details as format_roadkill_event_details,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    format_threat_event_details as format_threat_event_details,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    get_icmbio_sector_layer as get_icmbio_sector_layer,
)

download_event_attachments = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="download_event_attachments",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_icmbio.tasks import (
    gather_icmbio_dashboard as gather_icmbio_dashboard,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    generate_bimonthly_report as generate_bimonthly_report,
)
from ecoscope_workflows_ext_icmbio.tasks import (
    prepare_bimonthly_report_context as prepare_bimonthly_report_context,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    patrol_observations = (
        task(get_patrol_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("patrol_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=100,
            **(params.get("patrol_observations") or {}),
        )
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_observations,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    relocs = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrols_tz,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type__display",
                "patrol_serial_number",
                "patrol_subject",
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("relocs") or {}),
        )
        .call()
    )

    relocs_in_bounds = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("relocs_in_bounds")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=relocs,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("relocs_in_bounds") or {}),
        )
        .call()
    )

    trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=relocs_in_bounds, **(params.get("trajs") or {}))
        .call()
    )

    total_patrols = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_id",
            **(params.get("total_patrols") or {}),
        )
        .call()
    )

    total_patrols_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_patrols_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Número de patrulhas",
            decimal_places=0,
            data=total_patrols,
            **(params.get("total_patrols_sv") or {}),
        )
        .call()
    )

    total_distance = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs, column_name="dist_meters", **(params.get("total_distance") or {})
        )
        .call()
    )

    total_distance_km = (
        task(with_unit)
        .validate()
        .set_task_instance_id("total_distance_km")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            original_unit="m",
            new_unit="km",
            value=total_distance,
            **(params.get("total_distance_km") or {}),
        )
        .call()
    )

    total_distance_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_distance_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Quilômetros percorridos",
            decimal_places=2,
            data=total_distance_km,
            **(params.get("total_distance_sv") or {}),
        )
        .call()
    )

    total_participants = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("total_participants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            column_name="extra__patrol_subject",
            **(params.get("total_participants") or {}),
        )
        .call()
    )

    total_participants_sv = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_participants_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Participantes/operadores",
            decimal_places=0,
            data=total_participants,
            **(params.get("total_participants_sv") or {}),
        )
        .call()
    )

    patrol_stats = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("patrol_stats")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=trajs,
            groupby_cols=["extra__patrol_serial_number"],
            reset_index=True,
            summary_params=[
                {
                    "display_name": "Início",
                    "aggregator": "min",
                    "column": "extra__patrol_start_time",
                    "decimal_places": None,
                },
                {
                    "display_name": "Fim",
                    "aggregator": "max",
                    "column": "extra__patrol_end_time",
                    "decimal_places": None,
                },
                {
                    "display_name": "Distância percorrida (km)",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
                {
                    "display_name": "Tempo (h)",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                    "original_unit": "s",
                    "new_unit": "h",
                    "decimal_places": 2,
                },
            ],
            **(params.get("patrol_stats") or {}),
        )
        .call()
    )

    patrol_stats_renamed = (
        task(map_columns)
        .validate()
        .set_task_instance_id("patrol_stats_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_stats,
            rename_columns={"extra__patrol_serial_number": "ID da patrulha"},
            raise_if_not_found=False,
            retain_columns=None,
            drop_columns=None,
            duplicate_strategy="suffix",
            **(params.get("patrol_stats_renamed") or {}),
        )
        .call()
    )

    patrol_stats_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("patrol_stats_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=patrol_stats_renamed,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("patrol_stats_table") or {}),
        )
        .call()
    )

    patrol_stats_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_stats_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_stats_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_stats_table",
            **(params.get("patrol_stats_table_html") or {}),
        )
        .call()
    )

    patrol_stats_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_stats_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrulhas incluídas",
            data=patrol_stats_table_html,
            **(params.get("patrol_stats_table_sv") or {}),
        )
        .call()
    )

    spatial_features = (
        task(get_spatial_features)
        .validate()
        .set_task_instance_id("spatial_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("spatial_features") or {}))
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features,
            tooltip_columns=[],
            **(params.get("spatial_features_layer") or {}),
        )
        .call()
    )

    local_spatial_file = (
        task(load_local_spatial_file)
        .validate()
        .set_task_instance_id("local_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("local_spatial_file") or {}))
        .call()
    )

    local_spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("local_spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=local_spatial_file,
            tooltip_columns=[],
            **(params.get("local_spatial_features_layer") or {}),
        )
        .call()
    )

    map_overlays = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("map_overlays")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[spatial_features_layer, local_spatial_features_layer],
            **(params.get("map_overlays") or {}),
        )
        .call()
    )

    viewport_settings = (
        task(set_viewport_settings)
        .validate()
        .set_task_instance_id("viewport_settings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("viewport_settings") or {}))
        .call()
    )

    patrol_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("patrol_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=trajs, **(params.get("patrol_colormap") or {}))
        .call()
    )

    selected_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("selected_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_colormap,
            retain_columns=[
                "geometry",
                "column_color",
                "column_label",
                "extra__patrol_serial_number",
            ],
            raise_if_not_found=False,
            drop_columns=None,
            rename_columns=None,
            duplicate_strategy="suffix",
            **(params.get("selected_traj_cols") or {}),
        )
        .call()
    )

    trajs_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("trajs_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("trajs_legend_title") or {}))
        .call()
    )

    trajs_layer = (
        task(create_path_layer)
        .validate()
        .set_task_instance_id("trajs_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=selected_traj_cols,
            legend={
                "title": trajs_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params.get("trajs_layer") or {}),
        )
        .call()
    )

    patrol_map_view_state = (
        task(compute_view_from_geodataframes)
        .validate()
        .set_task_instance_id("patrol_map_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=trajs,
            viewport=viewport_settings,
            **(params.get("patrol_map_view_state") or {}),
        )
        .call()
    )

    patrol_map_layers = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("patrol_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[map_overlays, trajs_layer],
            **(params.get("patrol_map_layers") or {}),
        )
        .call()
    )

    patrol_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=patrol_map_layers,
            tile_layers=base_maps,
            static=False,
            title=None,
            view_state=patrol_map_view_state,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("patrol_map") or {}),
        )
        .call()
    )

    patrol_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=patrol_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="patrol_coverage.html",
            filename_suffix=None,
            **(params.get("patrol_map_url") or {}),
        )
        .call()
    )

    patrol_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa de trilhas de patrulha",
            data=patrol_map_url,
            **(params.get("patrol_map_widget") or {}),
        )
        .call()
    )

    time_density = (
        task(calculate_elliptical_time_density)
        .validate()
        .set_task_instance_id("time_density")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajectory_gdf=trajs,
            auto_scale_or_custom_cell_size={"auto_scale_or_customize": "Auto-scale"},
            crs="EPSG:3857",
            nodata_value="nan",
            band_count=1,
            max_speed_factor=1.05,
            expansion_factor=1.3,
            percentiles=["50", "60", "70", "80", "90", "99.999"],
            **(params.get("time_density") or {}),
        )
        .call()
    )

    time_density_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("time_density_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=time_density,
            input_column_name="percentile",
            output_column_name="percentile_color",
            colormap="RdYlGn",
            **(params.get("time_density_colormap") or {}),
        )
        .call()
    )

    time_density_layer = (
        task(create_polygon_layer_pydeck)
        .validate()
        .set_task_instance_id("time_density_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=time_density_colormap,
            layer_style={
                "get_fill_color": "percentile_color",
                "get_line_color": "percentile_color",
                "opacity": 0.55,
                "stroked": True,
                "filled": True,
                "line_width_units": "pixels",
            },
            legend={
                "title": "Densidade de tempo (percentil)",
                "label_column": "percentile",
                "color_column": "percentile_color",
            },
            data_url=None,
            tooltip_columns=None,
            **(params.get("time_density_layer") or {}),
        )
        .call()
    )

    time_density_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("time_density_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=[time_density_layer],
            tile_layers=base_maps,
            static=False,
            title=None,
            view_state=patrol_map_view_state,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("time_density_map") or {}),
        )
        .call()
    )

    time_density_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("time_density_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=time_density_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="patrol_time_density.html",
            filename_suffix=None,
            **(params.get("time_density_map_url") or {}),
        )
        .call()
    )

    time_density_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("time_density_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa de densidade de tempo",
            data=time_density_map_url,
            **(params.get("time_density_map_widget") or {}),
        )
        .call()
    )

    events_raw = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events_raw")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_types=[
                "caceria",
                "pesca_ilegal",
                "explorao_vegetal",
                "atropelamento_v2",
                "outras_ameaas",
                "armadilhas_fotogrficas",
                "retirada_armadilhas_fotogrficas",
            ],
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "serial_number",
                "event_details",
                "geometry",
                "reported_by",
            ],
            include_details=True,
            include_display_values=True,
            include_null_geometry=False,
            include_updates=False,
            include_related_events=False,
            force_point_geometry=True,
            raise_on_empty=False,
            **(params.get("events_raw") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_raw,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    events_details_resolved = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events_details_resolved")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            client=er_client,
            map_to_titles=True,
            ordered=True,
            **(params.get("events_details_resolved") or {}),
        )
        .call()
    )

    events_with_lat_lon = (
        task(add_lat_lon_to_gdf)
        .validate()
        .set_task_instance_id("events_with_lat_lon")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_gdf=events_details_resolved,
            **(params.get("events_with_lat_lon") or {}),
        )
        .call()
    )

    events_by_type = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("events_by_type")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_lat_lon,
            groupby_cols=["event_type_display"],
            reset_index=True,
            summary_params=[
                {"display_name": "Quantidade", "aggregator": "count", "column": "id"}
            ],
            **(params.get("events_by_type") or {}),
        )
        .call()
    )

    events_by_type_renamed = (
        task(map_columns)
        .validate()
        .set_task_instance_id("events_by_type_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_by_type,
            rename_columns={"event_type_display": "Tipo de evento"},
            raise_if_not_found=False,
            retain_columns=None,
            drop_columns=None,
            duplicate_strategy="suffix",
            **(params.get("events_by_type_renamed") or {}),
        )
        .call()
    )

    events_by_type_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("events_by_type_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=events_by_type_renamed,
            columns=None,
            table_config=None,
            **(params.get("events_by_type_table") or {}),
        )
        .call()
    )

    events_by_type_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("events_by_type_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=events_by_type_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="events_by_type_table",
            **(params.get("events_by_type_table_html") or {}),
        )
        .call()
    )

    events_by_type_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("events_by_type_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Eventos observados",
            data=events_by_type_table_html,
            **(params.get("events_by_type_table_sv") or {}),
        )
        .call()
    )

    sectors = (
        task(get_icmbio_sector_layer)
        .validate()
        .set_task_instance_id("sectors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("sectors") or {}))
        .call()
    )

    sector_centroids = (
        task(compute_sector_centroids)
        .validate()
        .set_task_instance_id("sector_centroids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(sectors_df=sectors, **(params.get("sector_centroids") or {}))
        .call()
    )

    camera_trap_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("camera_trap_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_lat_lon,
            column="event_type",
            values=["armadilhas_fotogrficas", "retirada_armadilhas_fotogrficas"],
            **(params.get("camera_trap_events") or {}),
        )
        .call()
    )

    camera_trap_sectors = (
        task(assign_sector)
        .validate()
        .set_task_instance_id("camera_trap_sectors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            points=camera_trap_events,
            sectors=sectors,
            **(params.get("camera_trap_sectors") or {}),
        )
        .call()
    )

    camera_trap_cols = (
        task(format_camera_trap_table)
        .validate()
        .set_task_instance_id("camera_trap_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=camera_trap_sectors, **(params.get("camera_trap_cols") or {}))
        .call()
    )

    camera_trap_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("camera_trap_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=camera_trap_cols,
            columns=None,
            table_config=None,
            **(params.get("camera_trap_table") or {}),
        )
        .call()
    )

    camera_trap_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("camera_trap_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=camera_trap_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="camera_trap_table",
            **(params.get("camera_trap_table_html") or {}),
        )
        .call()
    )

    camera_trap_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("camera_trap_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Armadilhas fotográficas",
            data=camera_trap_table_html,
            **(params.get("camera_trap_table_sv") or {}),
        )
        .call()
    )

    threat_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("threat_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_lat_lon,
            column="event_type",
            values=["caceria", "pesca_ilegal", "explorao_vegetal", "outras_ameaas"],
            **(params.get("threat_events") or {}),
        )
        .call()
    )

    threat_event_details = (
        task(format_threat_event_details)
        .validate()
        .set_task_instance_id("threat_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=threat_events, **(params.get("threat_event_details") or {}))
        .call()
    )

    threat_events_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("threat_events_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=threat_event_details,
            columns=None,
            table_config=None,
            **(params.get("threat_events_table") or {}),
        )
        .call()
    )

    threat_events_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("threat_events_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=threat_events_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="threat_events_table",
            **(params.get("threat_events_table_html") or {}),
        )
        .call()
    )

    threat_events_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("threat_events_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Ameaças",
            data=threat_events_table_html,
            **(params.get("threat_events_table_sv") or {}),
        )
        .call()
    )

    roadkill_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("roadkill_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_lat_lon,
            column="event_type",
            values=["atropelamento_v2"],
            **(params.get("roadkill_events") or {}),
        )
        .call()
    )

    roadkill_event_details = (
        task(format_roadkill_event_details)
        .validate()
        .set_task_instance_id("roadkill_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=roadkill_events, **(params.get("roadkill_event_details") or {}))
        .call()
    )

    roadkill_events_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("roadkill_events_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=roadkill_event_details,
            columns=None,
            table_config=None,
            **(params.get("roadkill_events_table") or {}),
        )
        .call()
    )

    roadkill_events_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("roadkill_events_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=roadkill_events_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="roadkill_events_table",
            **(params.get("roadkill_events_table_html") or {}),
        )
        .call()
    )

    roadkill_events_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("roadkill_events_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Atropelamentos",
            data=roadkill_events_table_html,
            **(params.get("roadkill_events_table_sv") or {}),
        )
        .call()
    )

    events_in_sectors = (
        task(assign_sector)
        .validate()
        .set_task_instance_id("events_in_sectors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            points=events_with_lat_lon,
            sectors=sectors,
            **(params.get("events_in_sectors") or {}),
        )
        .call()
    )

    grid_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("grid_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_in_sectors,
            groupby_cols=["sector"],
            reset_index=True,
            summary_params=[
                {"display_name": "Quantidade", "aggregator": "count", "column": "id"}
            ],
            **(params.get("grid_summary") or {}),
        )
        .call()
    )

    grid_summary_with_centroids = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("grid_summary_with_centroids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=grid_summary,
            right=sector_centroids,
            how="left",
            on=None,
            left_on="sector",
            right_on="name",
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("grid_summary_with_centroids") or {}),
        )
        .call()
    )

    grid_summary_renamed = (
        task(format_grid_summary_table)
        .validate()
        .set_task_instance_id("grid_summary_renamed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=grid_summary_with_centroids, **(params.get("grid_summary_renamed") or {})
        )
        .call()
    )

    grid_summary_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("grid_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=grid_summary_renamed,
            columns=None,
            table_config=None,
            **(params.get("grid_summary_table") or {}),
        )
        .call()
    )

    grid_summary_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("grid_summary_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=grid_summary_table,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="grid_summary_table",
            **(params.get("grid_summary_table_html") or {}),
        )
        .call()
    )

    grid_summary_table_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("grid_summary_table_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Resumo por setor",
            data=grid_summary_table_html,
            **(params.get("grid_summary_table_sv") or {}),
        )
        .call()
    )

    event_colormap = (
        task(apply_qualitative_color_map)
        .validate()
        .set_task_instance_id("event_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=events_with_lat_lon, **(params.get("event_colormap") or {}))
        .call()
    )

    event_legend_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("event_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("event_legend_title") or {}))
        .call()
    )

    event_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("event_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            legend={
                "title": event_legend_title,
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params.get("event_layer") or {}),
        )
        .call()
    )

    events_map_layers = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("events_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[map_overlays, event_layer],
            **(params.get("events_map_layers") or {}),
        )
        .call()
    )

    events_map_view_state = (
        task(compute_view_from_geodataframes)
        .validate()
        .set_task_instance_id("events_map_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_colormap,
            viewport=viewport_settings,
            **(params.get("events_map_view_state") or {}),
        )
        .call()
    )

    events_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("events_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=events_map_layers,
            tile_layers=base_maps,
            view_state=events_map_view_state,
            static=False,
            title=None,
            max_zoom=17,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("events_map") or {}),
        )
        .call()
    )

    events_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("events_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=events_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="events_map.html",
            filename_suffix=None,
            **(params.get("events_map_url") or {}),
        )
        .call()
    )

    events_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("events_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mapa de eventos",
            data=events_map_url,
            **(params.get("events_map_widget") or {}),
        )
        .call()
    )

    events_bar_chart = (
        task(draw_time_series_bar_chart)
        .validate()
        .set_task_instance_id("events_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=event_colormap,
            x_axis="time",
            y_axis="id",
            category="event_type_display",
            agg_function="count",
            time_interval="month",
            color_column="column_color",
            plot_style=None,
            layout_style={
                "showlegend": True,
                "legend_title": "Tipo de evento",
                "title": None,
                "title_x": 0.5,
                "font_size": None,
                "font_color": None,
                "font_style": None,
                "plot_bgcolor": None,
                "hovermode": None,
                "xaxis": None,
                "yaxis": None,
            },
            **(params.get("events_bar_chart") or {}),
        )
        .call()
    )

    events_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("events_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=events_bar_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="events_bar_chart",
            **(params.get("events_bar_chart_html") or {}),
        )
        .call()
    )

    events_bar_chart_sv = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("events_bar_chart_sv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Eventos de patrulha por mês",
            data=events_bar_chart_html,
            **(params.get("events_bar_chart_sv") or {}),
        )
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            event_gdf=event_colormap,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            **(params.get("download_attachments") or {}),
        )
        .call()
    )

    patrol_map_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("patrol_map_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=patrol_map_url,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("patrol_map_png") or {}),
        )
        .call()
    )

    time_density_map_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("time_density_map_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=time_density_map_url,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("time_density_map_png") or {}),
        )
        .call()
    )

    events_map_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("events_map_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=events_map_url,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 720,
                "full_page": True,
                "device_scale_factor": 2,
                "wait_for_timeout": 240000,
                "timeout": 0,
                "max_concurrent_pages": 5,
                "serve_local_files": False,
            },
            **(params.get("events_map_png") or {}),
        )
        .call()
    )

    report_template_path = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("report_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("report_template_path") or {}))
        .call()
    )

    report_context = (
        task(prepare_bimonthly_report_context)
        .validate()
        .set_task_instance_id("report_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            time_range=time_range,
            total_patrols=total_patrols,
            total_distance_km=total_distance_km,
            total_participants=total_participants,
            patrols=patrol_stats_renamed,
            events_summary=events_by_type_renamed,
            camera_traps=camera_trap_cols,
            threats=threat_event_details,
            roadkill=roadkill_event_details,
            grid_summary=grid_summary_renamed,
            **(params.get("report_context") or {}),
        )
        .call()
    )

    patrol_report = (
        task(generate_bimonthly_report)
        .validate()
        .set_task_instance_id("patrol_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context=report_context,
            template_path=report_template_path,
            patrol_map_png=patrol_map_png,
            time_density_map_png=time_density_map_png,
            events_map_png=events_map_png,
            photo_attachment_paths=download_attachments,
            photo_events=event_colormap,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("patrol_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_icmbio_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_patrols_sv,
                total_distance_sv,
                total_participants_sv,
                patrol_stats_table_sv,
                events_by_type_table_sv,
                threat_events_table_sv,
                roadkill_events_table_sv,
                camera_trap_table_sv,
                grid_summary_table_sv,
                patrol_map_widget,
                time_density_map_widget,
                events_map_widget,
                events_bar_chart_sv,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
